async function loadDashboardData() {
  const res = await fetch('../data/dashboard_data.json', { cache: 'no-store' });
  if (!res.ok) throw new Error('Unable to load dashboard data');
  return await res.json();
}
function statCard(label, value, small='') { return `<div class="card"><div class="label">${label}</div><div class="value">${value}</div><div class="small">${small}</div></div>`; }
function predictionCard(p) {
  const scorelines = (p.top_scorelines || []).map(s => `${s.score} (${(s.probability*100).toFixed(1)}%)`).join(', ');
  return `<div class="match"><div class="row" style="justify-content:space-between;align-items:center;"><span class="pill">${p.selected_model || 'baseline_main'}</span><span class="meta">${p.kickoff_utc || ''}</span></div><div class="teams">${p.home_team} vs ${p.away_team}</div><div class="meta">${p.stage || '-'} ${p.group ? '• Group ' + p.group : ''} ${p.venue ? '• ' + p.venue : ''}</div><div class="prob">Pick: <strong>${p.predicted_outcome}</strong> (${(p.confidence*100).toFixed(1)}%)</div><div class="prob">Win probs: ${p.home_team} ${(p.home_win_prob*100).toFixed(1)}% • Draw ${(p.draw_prob*100).toFixed(1)}% • ${p.away_team} ${(p.away_win_prob*100).toFixed(1)}%</div><div class="prob">Expected goals: ${p.expected_goals_home?.toFixed(2)} - ${p.expected_goals_away?.toFixed(2)}</div><div class="prob">Likely scorelines: ${scorelines || 'N/A'}</div><div class="prob">Simulations: ${p.simulation_runs}</div></div>`;
}
function render(data) {
  const preds = data.predictions_today || []; const backtest = data.backtest || {}; const comparison = data.model_comparison || {}; const models = comparison.models || [];
  document.getElementById('heroStats').innerHTML = [statCard('Selected model', data.selected_model || 'N/A', 'Auto-selected best model'), statCard('Predictions today', preds.length, 'Upcoming matches tracked'), statCard('Latest accuracy', backtest.pick_accuracy != null ? (backtest.pick_accuracy*100).toFixed(1) + '%' : 'N/A', 'Backtest pick accuracy'), statCard('Simulation runs', preds[0]?.simulation_runs || 0, 'Per match simulation count')].join('');
  document.getElementById('predictionsGrid').innerHTML = preds.length ? preds.map(predictionCard).join('') : '<div class="card">No predictions available.</div>';
  document.getElementById('modelStats').innerHTML = [statCard('Backtest Brier', backtest.brier_score != null ? Number(backtest.brier_score).toFixed(4) : 'N/A', 'Lower is better'), statCard('Backtest Log Loss', backtest.log_loss != null ? Number(backtest.log_loss).toFixed(4) : 'N/A', 'Lower is better'), statCard('Best compared model', comparison.best_model || 'N/A', 'From latest comparison'), statCard('Generated at', data.generated_at_utc || 'N/A', 'UTC timestamp')].join('');
  document.getElementById('comparisonBody').innerHTML = models.map(m => `<tr><td>${m.model_name}</td><td>${((m.pick_accuracy || 0) * 100).toFixed(1)}%</td><td>${m.brier_score != null ? Number(m.brier_score).toFixed(4) : 'N/A'}</td><td>${m.log_loss != null ? Number(m.log_loss).toFixed(4) : 'N/A'}</td><td>${m.ece != null ? Number(m.ece).toFixed(4) : 'N/A'}</td></tr>`).join('');
  const upcomingBtn = document.getElementById('showUpcomingBtn'); const upcomingPanel = document.getElementById('upcomingPanel');
  upcomingBtn.onclick = () => { const next = preds[0]; if (!next) { upcomingPanel.style.display = 'block'; upcomingPanel.innerHTML = '<div class="label">Upcoming Match</div><div class="value">No upcoming match available</div>'; return; } upcomingPanel.style.display = 'block'; upcomingPanel.innerHTML = `<div class="label">Current Upcoming Match Prediction</div><div class="value" style="font-size:22px;">${next.home_team} vs ${next.away_team}</div><div class="small">Pick: ${next.predicted_outcome} (${(next.confidence*100).toFixed(1)}%)</div><div class="small">Win probs: ${next.home_team} ${(next.home_win_prob*100).toFixed(1)}% • Draw ${(next.draw_prob*100).toFixed(1)}% • ${next.away_team} ${(next.away_win_prob*100).toFixed(1)}%</div><div class="small">Expected goals: ${next.expected_goals_home?.toFixed(2)} - ${next.expected_goals_away?.toFixed(2)}</div>`; if (window.Telegram?.WebApp) { window.Telegram.WebApp.HapticFeedback?.impactOccurred?.('light'); } };
}
async function startApp() { if (window.Telegram?.WebApp) { window.Telegram.WebApp.ready(); window.Telegram.WebApp.expand(); } render(await loadDashboardData()); }
document.getElementById('refreshBtn').onclick = async () => render(await loadDashboardData()); startApp().catch(err => { document.getElementById('predictionsGrid').innerHTML = `<div class="card">Failed to load dashboard data: ${err}</div>`; });
